### PR TITLE
Implement local mode; auto-refresh using javascript; Makefile path override; better handling of html from cgi scripts; add global docker config; add fine-grained docker controls

### LINKED ISSUE #51: Implement "local" mode
Sometimes it's convenient to run DROID locally. Right now technical people can do this with a bit of work, but it would be good to make it easier for non-technical people.

The main thing is just to run a single JAR file, but there's a few complications:

1. DROID currently expects a Python environment #39 but we can eliminate this
2. DROID wants to authenticate users with GitHub OAuth

The current solution to 2 is to create an OAuth App pointing to localhost, and provide the Client ID and Client Secret to DROID. With some changes we could make DROID accept a single user's Personal Access Token. Since we need to talk to GitHub API, I don't see how we can eliminate this, but we want to make it as easy as possible.

@matentzn suggested that more control over the working directories would also be good. Keep in mind that DROID is designed around a correspondence between: one branch, one working directory, one Docker container (optional), and one working process. Users can mess around in the working directory, running commands and editing files and doing pretty much anything, even `git pull` and `git push`, but one thing they must not do is change the git branch (`git checkout some_other_branch`), or DROID will be very confused.

@matentzn also suggested Dockerizing DROID. The main problem I see with that is controlling other Docker containers from within a Docker container: that used to be difficult or impossible, but maybe things have changed. But Docker containers are optional for DROID, so running DROID inside Docker should be fine if DROID is not also trying to run its own Docker containers.

### LINKED ISSUE #58: User feedback: "Pressing refresh is 'a bit annoying' "
Maybe we can make it possible to periodically refresh the view for long running tasks.

### LINKED ISSUE #77: Add global docker config to be used as a fallback if a project doesn't define one
The configuration file `config.edn` should contain an entry for a global docker configuration that will be used in case a particular project doesn't have its own.

### LINKED ISSUE #78: Add fine-grained controls and indicators for project-level and branch-specific images
We should add some more information and controls to the branch page. In particular we can add another column to the displayed table with a heading like "image status" as well as a small button next to it that a site-admin can use to recreate a branch-specific image if there isn't one already. In addition we can have another indicator at the top (or bottom) of the table with the status of the project-level image along with a button to rebuild it.

### LINKED ISSUE #85: Implement configurable override for Makefile path
Coming out of the general discussion in #46, @matentzn and I agreed on one specific new DROID feature to implement now: We would like a configuration option `:makefile-path` at the project level to provide a relative path to a Makefile inside the branch. The default will be the top-level Makefile for the branch, which is the current behaviour. This Makefile should be used to read the Workflow section and to run Make tasks from that Makefile from that directory.

For example:

```
"ZECO"
{:project-title "Zebrafish Experimental Conditions Ontology"
 :project-welcome "welcome message"
 :project-description "description"
 :github-coordinates "jamesaoverton/zebrafish-experimental-conditions-ontology"
 :makefile-path "src/ontology/Makefile"
 :docker-config
 {:active? true
  :image "obolibrary/odkfull"
  :workspace-dir "/workspace/"
  :temp-dir "/tmp/droid/"
  :default-working-dir "/workspace/"
  :shell-command "bash"
  :env {"ENV_VAR_1" "env_var_1_value"}}} 
```

### LINKED ISSUE #86: Bug: DROID unable to actually kill running processes that are running in docker
I'm surprised no one noticed this before, but while processes are successfully killed after pressing the Cancel (or Kill) button when DROID is running in non-docker mode, this doesn't work for processes running in docker. At least it doesn't work in my setup.

### PR DESCRIPTION
**Pull request by lmcmicu**
Closes #51 
Closes #58 
Closes #85 
Partially implements #76 
Closes #77 
Closes #78 
Closes #86

### CODE REVIEW

**Comment by lmcmicu** [comment]
I need to convert this back to draft mode temporarily as I just noticed that the javascript change has broken something minor with respect the the "multiple tabs" implementation of views.

**Comment by lmcmicu** [comment]
Nevermind about that. I didn't actually break anything, I just forgot that that was the desired behaviour. Changing this back into "Ready for review" state.

**Comment by lmcmicu** [comment]
Converting back to draft while I continue to work on #85

**Comment by jamesaoverton** [comment]
Actually let's change the example to `src/ontology/custom.Makefile`

**Review by jamesaoverton — APPROVED** [review]

**Pull request merged**
