### PR TITLE
Miscellaneous fixes and improvements

### LINKED ISSUE #45: Figure out how to handle secrets
Some of the CGI scripts we're developing need access to credentials. Specifically, [COGS](https://github.com/ontodev/cogs) needs to read a JSON file with secrets in order to talk to Google Sheets.

1. My first thought was that DROID can be configured (in `config.edn`) to store some secrets and pass the to Make or CGI scripts in as environment variables. This works fine whether the task is running inside Docker on just on the server. We probably want to be able to do this.

2. Unfortunately the [gpread](https://gspread.readthedocs.io/en/latest/oauth2.html#for-bots-using-service-account) library we're using really expects a file. So my second thought was to create a `projects/FOO/secrets` directory that tasks can just read. But that make it harder for tasks to find the file, and probably means we have to mount another volume for Docker.

3. My current best idea is to create an optional `projects/FOO/configuration/` directory and then copy the contents into the workspace of each branch when the branch is created. (Maybe also on startup, or on file change?) My main worry with this approach is that it's pretty easy to accidentally reveal these files. Maybe DROID could blacklist these files and refuse to serve them. If the scripts/tasks in the repo reveal these credentials, then it's not really DROID's fault.

If it's just COGS that needs this, then maybe should just hack COGS to read an environment variable into the file that it needs.

Better ideas?

### LINKED ISSUE #101: Move easily from GitHub to DROID
We've built various links from DROID back to GitHub repos, branches, and PRs. But how should users navigate from GitHub to DROID? Say they're looking at a PR on GitHub and want to check out and test that PR in DROID.

1. links in PR comments: When DROID creates a PR it could add a link to the message. We could also do this for commit messages. I kind of hate this though. It seems noisy and distracting.
2. webextension: On Zoom I often see people who must have a browser web extension install that adds tabs and links and stuff to GitHub. That's very powerful. But I think it's still really hard to make a single cross-browser extension, and developing an extension for every browser would be a pain. Worse, we'd have to get users to install the extension. As a user I would hate that.
3. DROID URL "interpreter" and bookmarklet: We could add a GET route and HTML form to DROID that will read a URL like <https://github.com/obi-ontology/obi/pull/1337> and then do smart stuff such as redirecting to an existing branch page, offering to check out the branch (for a PR), or start a new branch (for an issue), or create a new project (for a repo). If you're on a GitHub page, a tiny bit of JavaScript in a [bookmarklet](https://en.wikipedia.org/wiki/Bookmarklet) could read the current GitHub URL and open a new tab for this DROID URL, like <https://droid.ontodev.com/?remote=https://github.com/obi-ontology/obi/pull/1337>.

I think 3 strikes a good balance. Any suggestions or alternatives?

### LINKED ISSUE #103: Address User-to-server token expiration
If I have recently logged in to DROID and I go to a project page, e.g. <https://droid.ontodev.com/ONTIE>, then I can see a list of all branches that I see on GitHub for that project.

If I logged in a few days ago, DROID will still say that I'm logged in, but if I go to a project page then I will only see the local branches. Logging out and then back in fixes the problem.

### LINKED ISSUE #104: When following the console, scroll to bottom on each refresh
When I start a task and then click "Follow console", the page will refresh every five seconds as expected. But if a bunch of console lines are added then I have to scroll down to the bottom of the page to see them. I would prefer the scrolling to be automatic, which matches the behaviour of Travis and GitHub Actions.

Maybe this could be implemented with a simple anchor at the bottom of the page, or maybe with a bit of JavaScript.

### LINKED ISSUE #105: Fetch after branch creation?
On the project page in the "Git status" column I sometimes see "Not yet fetched". I think this occurs when a new branch is created. I think it would be better to just fetch so this information is available.

### LINKED ISSUE #106: Add a Troubleshooting section to the README
We can expand on this later, but for now it should just recommend increasing the logging level in `config.edn` and show how that's done.

### PR DESCRIPTION
**Pull request by lmcmicu**
Fixes #103, closes #106, closes #104, closes #105, closes #45, closes #101

**Note:** After applying this change, please
* Stop droid.
* Remove the `db/` sudirectory in DROID's main directory
* Restart DROID.

Any previously logged in users will then have to log in again. (This only needs to be done once.)

### CODE REVIEW

**Comment by lmcmicu** [comment]
Unfortunately I need to convert this PR back into draft mode. Upgrading the ring library has had an impact on the way `joda-time` objects are stored in the ring header which requires us to 'unquarantine' them before reading them. Some code was added to handle this but it seems it is not working correctly.

I think we should consider reversing the upgrade of `ring` here and opening a new (small) PR to deal just with this upgrade; i.e.,
- reverse the upgrade of the ring library
- merge this PR once it has been tested
- open a new PR to deal with the upgrade of ring.

**Comment by jamesaoverton** [comment]
I finally got a chance to deploy and test this. I noticed one (hopefully) small change I would like, and everything else looks exactly right.

The one small change is that when you click "Follow console", the page should scroll to the bottom right away. Currently it waits five seconds and then scrolls to the bottom.

**Comment by lmcmicu** [comment]
Ok, I have just pushed a commit (https://github.com/ontodev/droid/pull/108/commits/7b1615cbcf9afeaafc33907abc4b49eb9d46fde0) to scroll to the bottom of the page after the page is loaded whenever auto-refresh is set.

**Review by jamesaoverton — APPROVED** [review]
Great! Please merge this.

**Pull request merged**
