### PR TITLE
Create wizard

### PR DESCRIPTION
**Pull request by beckyjackson**
The wizard gets user input to create the config file. It automatically creates the GitHub repo link from the inputs and check if the GitHub page resolves.

Note that this requires the `requests` module, which may need to be installed. I'm open to other ways of checking to prevent the need for this...

### CODE REVIEW

**Comment by jamesaoverton** [comment]
Good. One thing: I don't want the `droid.yml` file to contain redundant information (Don't Repeat Yourself). So the 'GitHub repository' key in the `droid.yml` unless it is different from the default -- which is not a case that the wizard should handle.

**Comment by beckyjackson** [comment]
Makes sense! Removed.

**Comment by jamesaoverton** [comment]
Testing this I got `ModuleNotFoundError: No module named 'requests'`

**Comment by beckyjackson** [comment]
Yeah, that's what I made a comment about above. I use it to check if the GH url resolves, but it's a module that may need to be downloaded. Do you know if there's something included in python that can be used instead?

**Comment by jamesaoverton** [comment]
We can use `requests` as long as it's added to `requirements.txt`, and thus loaded with `pip install -r requirements.txt`.

**Comment by beckyjackson** [comment]
Perfect. Done!

**Pull request merged**
